@extends('layouts.page')

@section('title', 'Adatvédelmi tájékoztató | Alföldy Dóra')

@section('page')
    <x-sections.rich-text title="Adatvédelmi tájékoztató" width="w-[93%] md:w-[75%]">
        <p>Az adatvédelmi tájékoztató a <a href="https://doraalfoldy.com">https://doraalfoldy.com</a> oldalon történő böngészéshez. Adatkezelési irányelvek, adatkezelés módja és ideje, adatkezelők…<br><br>A weboldalak témái: kozmetikai szolgáltatások, szempilla, szemöldök és smink készítése.</p>
        
        <p>1. Az adatkezelő: A weboldal látogatása során az Ön adatainak felelős kezelője Alföldy Dóra Egyéni Vállalkozó. Székhely: 1139 Budapest, Röppentyű utca 25/29. B épület Fsz. 1. Adószám: 57332422-1-41. E-mail cím: <a href="mailto:info@doraalfoldy.com">info@doraalfoldy.com</a>. Telefon. <a href="tel:+36309710393">+36 30 971 0393</a>. Adatvédelmi felelős: Alföldy Gábor</p>
        
        <p>Az adatkezelés célja lehet: – Az ügyfelekkel való kapcsolattartás árajánlathoz, rendelt termék kiszállításához. – Tájékoztató anyag küldése, adott ajánlathoz, vagy megrendeléshez kapcsolódva. Az adatkezelés időtartama az alábbiak figyelembevételével kerül meghatározásra: – ajánlat érvényessége, – megrendelés státusza, – garanciális időszak időtartama.</p>
        
        <h2>Személyes adatok</h2>
        <p>Amikor Ön a https://doraalfoldy.com internetes honlapot látogatja, eközben személyes adatait is átadja számunkra. Személyes adatai (azaz azok az adatok, amelyek az Ön személyével kapcsolatba hozhatók) a következő módon kerülhetnek a kezelésünkbe:<br><br>– egyfelől az internetes kapcsolat fenntartásával összefüggésben az Ön által használt számítógéppel, böngészőprogrammal, internetes címmel, a látogatott oldalakkal kapcsolatos technikai adatok automatikusan képződnek számítógépes rendszerünkben,<br><br>– másfelől Ön is megadhatja nevét, elérhetőségét vagy más ügyfélkapcsolati adatait, ha a honlap használata során személyes kapcsolatba kíván lépni velünk.<br><br>A weboldalon lévő legtöbb információ megtekintéséhez regisztráció vagy bejelentkezési adatok megadása nem szükséges. Vannak azonban olyan funkciók, melyek igénybevételéhez bizonyos személyes adatok megadására (név, e-mail cím) szükség lehet. Az Ön hozzájárulásával az alábbi ügyfélkapcsolati adatait kezeljük : név, E-mail cím, telefonszám, levelezési és szállítási cím.</p>
        
        <h2>Hozzájárulás</h2>
        <p>Ön a honlap látogatásával hozzájárulását adja a 2. pontban jelzettek szerint automatikusan képződő adatok kezeléséhez. Amennyiben Ön bármely személyes adatát eljuttatja Alföldy Dóra EV-hoz, az adatok megadásával önkéntes hozzájárulását adja ahhoz, hogy Alföldy Dóra EV – az ügylet jellege által meghatározott célból és ideig – azt nyilvántartsa és kezelje.</p>
        
        <h2>Az adatkezelés mértéke, elvei</h2>
        <p>Az Ön személyes adatainak kezelése csak a honlap szolgáltatásainak igénybevételéhez szükséges mértékben, illetve az Ön rendelkezésének megfelelően, egyúttal a hatályos jogszabályi rendelkezések maradéktalan betartásával történik. Ezen felül blogbejegyzéshez kérjük el az Ön adatait és csak a szükséges mértékben. Alföldy Dóra EV az Ön által az Interneten keresztül megadott személyes jellegű adatokat kiemeltebb biztonsági fokú védelemmel kezelje, mint az egyéb úton rendelkezésre bocsátott adatokat. Az oldal SSL tanúsítvánnyal rendelkezik, mely garantálja az adatok biztonságát a szerveren. Ugyanilyen kiemelten kezeljük belső IT rendszerünket is. Ön az adatkezelés során bármikor tájékoztatást kérhet, illetve ellenőrizheti adatai tartalmát, igény szerint bármikor kérheti azok helyesbítését, módosítását, megváltoztatását, illetve törlését. Alföldy Dóra EV. az Ön kérelmének 5 munkanapon belül tesz eleget. Ön az adatkezeléshez történő hozzájárulását bármikor módosíthatja, illetve visszavonhatja. Az Ön személyes adatait a közöttünk fennálló üzleti kapcsolat időtartama alatt kezeljük. A fenti rendelkezések nem érintik a jogszabályban meghatározott, például számviteli előírásokból fakadó megőrzési kötelezettségek teljesítését. Az Adatkezelő ügyfelei által igénybe vett szolgáltatások adatai megjelennek a számlán és egyéb számviteli bizonylatokon is, ezek az adatok a számviteli előírások miatt nem törölhetők.</p>
        
        <h2>Az adatkezelők köre</h2>
        <p>Alföldy Dóra EV a tudomására jutott adatokat harmadik személy számára – a jogszabályban rögzített eseteken kívül – semmilyen körülmények között nem adja ki. A honlap látogatásával összefüggésben kezelt adataihoz saját munkatársaink férnek hozzá, kizárólag a feladatuk ellátásához, illetve az Ön által igénybe vett szolgáltatás teljesítéséhez, esetleges kérdésének, észrevételének megválaszolásához szükséges mértékben. Alföldy Dóra EV. a weboldal üzemeltetéséhez és egyben a látogatók adatainak kezeléséhez külső szervezetet (adatfeldolgozókat) is igénybe vesz.<br><br>Tárhely szolgáltató: <strong>ACWS</strong> Szolgáltató Bt., Felelős személy Lévai Gábor, E-mail: <a href="mailto:domains@acwsbt.com">domains@acwsbt.com</a>, Cím: 1145 Budapest, Újvilág utca 39/A., Tel.: <a href="tel:+36302107552">+36 30 210 7552</a>. Adatvédelmi szabályzatuk letölthető a https://directhosting.hu/adatkezelesi-tajekoztato/ címről.<br><br>Alföldy Dóra EV. a termékeinek kiszállításához külső alvállalkozót (szállítót) vehet igénybe. Külső vállalkozó: GLS Hungary Csomag-LogisztikaiKft. E-mail: info@gls-hungary.com Cím: 2351 Alsónémedi, GLS Europa u. 2. Tel.: +36 1 802 0265 Honlap: www.gls-hungary.com<br><br>Alföldy Dóra EV. a kártyás fizetést a Barion Payment ZRt. rendszerén keresztül biztosítja. Székhely: 1117 Budapest, Infopark sétány 1. I. épület 5. emelet 5. Nyilvántartó cégbíróság: Fővárosi Törvényszék Cégbírósága. Cégjegyzékszám: Cg. 01-10-048552 Adószám: 25353192-2-43. Közösségi adószám: HU25353192 Tevékenységi engedély száma: H-EN-I-1064/2013 Elektronikuspénz-kibocsátó intézményi azonosító: 25353192Az adatvédelmi tisztviselő elérhetőségei: Kövecses-Varga Márton, Barion Payment Zrt. Cím: 1117 Budapest, Infopark sétány 1. I. épület 5. emelet 5 E-mail: compliance@barion.com, Telefonszám: +36 1 464 7099. A Barion Payment ZRt. adatvédelmi tájékoztatója a https://www.barion.com/hu/adatvedelmi-tajekoztato/ linken olvasható és tölthető le.</p>
        
        <h2>Kapcsolatfelvétel</h2>
        <p>Amennyiben Ön kérdést intéz hozzánk vagy kifejti valamilyen témában véleményét, a kapcsolat oldali elérhetőségeket is használhatja. Ilyenkor meg kell adnia nevét, elektronikus postacímét (e-mail), esetleg telefonszámát, valamint kérdését vagy véleményét. Ha további tájékoztatást szeretne adatainak kezeléséről, forduljon hozzánk elektronikus levélben, telefonon vagy postai úton az alábbi elérhetőségeken: Alföldy Dóra EV. cím: 1139 Budapest, Röppentyű utca 25-29. B. épület fsz. 1. e-mail: <a href="mailto:info@doraalfoldy.com">info@doraalfoldy.com</a> tel.: <a href="tel:+36309710393">+36 30 971 0393</a> honlap: https://doraalfoldy.com</p>
        
        <h2>Sütik</h2>
        <p>Alföldy Dóra EV, szolgáltatásai színvonalának emelése, a felhasználó azonosítása, a felhasználó további látogatásainak megkönnyítése, a szolgáltatás hatékonyságának növelése, az adott felhasználó számára célzott reklám, vagy egyéb célzott tartalom eljuttatása, vagy piackutatás céljából, illetve a biztonsági és adatvédelmi kockázatok megfelelő kezelése érdekében ún. sütiket („cookie”) használ. A cookie egy olyan kis adategyüttes, amelyet ez a webhely az Ön számítógépének böngészőprogramjában tárol és később onnan kiolvashat. A cookie-t más webhely nem képes elolvasni, csak az amelyik azt elhelyezte. A cookie-t Alföldy Dóra EV. adminisztratív célokra használja fel, mint például a weboldal látogatottságának mérése. Egy cookie sem tartalmaz olyan személyes adatot, amely lehetővé tenné bárki számára az Ön e-mailen, telefonon vagy hagyományos postai úton történő elérését.<br><br>Önnek böngészőjében a cookie-k vonatkozásában az alábbi lehetőségei vannak:<br>– beállíthatja, hogy értesítést kapjon arról, ha a weblap üzemeltetője cookie-t kíván elhelyezni a számítógépén,<br>– a cookie-k küldését bármikor megtilthatja. Fontos, hogy a cookie-k el nem fogadása azt eredményezi, hogy ezzel összefüggésben bizonyos oldalak vagy funkciók nem működnek megfelelően, valamint lehetséges, hogy a Ön nem kap jogosultságot bizonyos adatokhoz való hozzáféréshez.<br><br>A cookie-kal kapcsolatos további információ a http://www.cookiecentral.com címen érhető el.<br><br>A kártyás fizetés üzemeltetéséhez, biztonsági szintjének emeléséhez a Barion Payment ZRt. szintén használ sütiket. Ennek részleteiről a https://www.barion.com/hu/suti-tajekoztato/ oldalon tájékozódhat.</p>
        
        <h2>Mérőkódok</h2>
        <p>A weboldal böngészése közbeni felhasználói viselkedés elemzése céljából Alföldy Dóra EV. harmadik személytől származó mérőkódokat (web beacon-t) használ. A web beacon egy olyan, weboldalba ágyazott kép, amely segítségével nyomon követhetőek a honlapon tett látogatások. Ezekkel az adatokkal elemezhetőek a látogatási szokások, amely a honlap minőségének javításához vagy a hirdetések megjelenítésével összefüggésben szükséges. A web beacon-ök funkciójukat tekintve hasonlítanak a cookie-khoz, azokat a felhasználók online mozgásának a nyomon követésére használják. A kettő között az a fő különbség, hogy a web beacon-ök nem láthatók az oldalon.<br><br>Mindemellett a felhasználónak nincsen arra lehetősége, hogy a web beacon-ök letöltését – a cookie-kkal ellentétben – letiltsa böngészőjében. További információ a web beaconökkel kapcsolatban: http://en.wikipedia.org/wiki/Web_beacon A weboldalon a látogató böngészési útvonalát A Google analytics, a facebook pixel és esetlegesen más cégek is rögzíthetik. Az így rögzített adatokat az oldal kezelője nem láthatja, annak csak statisztikai kivonataihoz férhet hozzá. Így az egyes látogatok konkrét tevékenységéről nincs információja. Ezen információkat marketing tevékenységének általános javítására használja csak fel.</p>
        
        <h2>Jogérvényesítési lehetőségek</h2>
        <p>Amennyiben adatkezelési gyakorlatunkkal kapcsolatban panasszal kíván élni, erre két lehetősége van. Javasoljuk, hogy panaszának mielőbbi orvoslása érdekében, bármely eljárás kezdeményezése előtt küldje meg panaszát Alföldy Dóra EV. részére.<br><br>– Nemzeti Adatvédelmi és Információszabadság Hatósághoz fordulhat, az alábbi elérhetőségeken: postacím: 1125 Budapest, Szilágyi Erzsébet fasor 22. telefon: 061-391-1400 e-mail: <a href="mailto:ugyfelszolgalat@naih.hu">ugyfelszolgalat@naih.hu</a> Web naih.hu – Ön jogainak védelme érdekében bírósághoz fordulhat, a pert az Ön lakóhelye, vagy tartózkodási helye szerint illetékes törvényszék előtt is megindíthatja.</p>
    </x-sections.rich-text>
@endsection
